name: Check lockfile
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  bunLockCheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - uses: actions/checkout@v4
      
      - uses: oven-sh/setup-bun@v1

      - name: check lock diff
        run: diff <(bun bun.lockb) yarn.lock
